[deps]
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
pandoc_jll = "c5432543-76ad-5c9d-82bf-db097047a5e2"
